# Generated by Django 5.0.6 on 2024-06-01 08:11

import parsers.checker
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', parsers.checker.ContentTypeRestrictedFileField(upload_to='uploads/')),
            ],
        ),
    ]
